import type { Metadata } from "next";
import { JetBrains_Mono, Manrope, Geologica } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/core/NavBar";
import Contact from '@/components/landing/dev2/contact'

const defaultUrl = "https://anagha-nisakar-portfolio.vercel.app/";

const geistSans = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Anagha Nisakar | Frontend Developer",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  metadataBase: new URL(defaultUrl),
  openGraph: {
    title: 'Anagha Nisakar | Frontend Developer | React,Next,Vue & Nuxt',
    description: 'Frontend Developer skilled in Vue, Nuxt, React, and Next.js, building fast, responsive, user-focused interfaces with clean code and modern rich UI experience.',
    type: "website",
    siteName: 'Anagha Nisakar\'s Developer Portfolio',
    images: [
      {
        url: 'https://anagha-nisakar-portfolio.vercel.app/opengraph-image.png',
        width: 1200,
        height: 1200,
        alt: 'Anagha Nisakar | Frontend Developer Portfolio Logo',
      }
    ],
  },
  twitter: {
    title: 'Anagha Nisakar\'s Developer Portfolio',
    description: 'Frontend Developer skilled in Vue, Nuxt, React, and Next.js, building fast, responsive, user-focused interfaces with clean code and modern rich UI experience.',
    images: [
      {
        url: 'https://anagha-nisakar-portfolio.vercel.app/twitter-image.png',
        width: 1200,
        height: 1200,
        alt: 'Anagha Nisakar | Frontend Developer Portfolio Logo',
      }
    ],
  },

  keywords: "Frontend Developer, Front-end Engineer, Front-end Web Developer, Web Developer, React.js Developer, Next.js Developer, Vue.js Developer, Nuxt.js Developer, Tailwind CSS Developer, SCSS Developer, HTML Developer, JavaScript Developer, Responsive Web Design, Modern UI Design, UI/UX Frontend, Figma to Frontend, Pixel Perfect UI, Clean Code Developer, Performance Optimization, Developer-side SEO, On-page SEO, Semantic HTML, Accessibility Developer, Web Application Developer, Frontend Freelancer, Portfolio Developer, Component-based Architecture, Reusable UI Components, API Integration, Modern Web Technologies",

  robots: { index: true, follow: true },
  alternates: {
    canonical: defaultUrl,
    languages: {
      "en-US": `${defaultUrl}/`,             // English - default
      // "fr": `${defaultUrl}/fr`,              // French
      // "es": `${defaultUrl}/es`,              // Spanish
      // "x-default": `${defaultUrl}/`,         // Fallback default
    },
  },
  authors: [
    {
      name: 'Anagha Nisakar',
      url: defaultUrl,
    },
  ],
  category: 'Frontend Developer Portfolio, Web Developer Portfolio, Software Developer Portfolio, UI/UX & Frontend Portfolio, JavaScript Developer Portfolio, React Developer Portfolio, Next.js Developer Portfolio, Vue.js Developer Portfolio, Nuxt.js Developer Portfolio, Tailwind CSS Developer Portfolio, IT & Software Development, Web Design & Development, Technology / Personal Portfolio, Creative Developer Portfolio',
  // other: {
  //   'script[type="application/ld+json"]': JSON.stringify({
  //     "@context": "https://schema.org",
  //     "@type": "Person",
  //     "@id": "https://anagha-nisakar-portfolio.vercel.app/#anaghanisakar",
  //     "name": "Anagha Nisakar",
  //     "jobTitle": "Frontend Developer",
  //     "image": "https://anagha-nisakar-portfolio.vercel.app/profile-photo.png",
  //     "url": "https://anagha-nisakar-portfolio.vercel.app/",
  //     "telephone": "+91 9072144202",
  //     "address": {
  //       "@type": "PostalAddress",
  //       "streetAddress": "Lakshmi Nivas, Kootalida, Avidanallur",
  //       "addressLocality": "Kozhikode",
  //       "addressRegion": "KL",
  //       "postalCode": "673614",
  //       "addressCountry": "IN"
  //     },
  //     "sameAs": [
  //       "https://www.linkedin.com/in/anagha-nisakar",
  //       "https://github.com/Anagha-Nisakar"
  //     ],
  //     "skills": [
  //       "React.js",
  //       "Next.js",
  //       "Vue.js",
  //       "Nuxt.js",
  //       "Tailwind CSS",
  //       "JavaScript",
  //       "UI/UX",
  //       "Responsive Web Development"
  //     ]
  //   })
  // },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "name": "Anagha Nisakar",
              "url": "https://anagha-nisakar-portfolio.vercel.app/",
              "jobTitle": "Frontend Developer",
              "image": "https://anagha-nisakar-portfolio.vercel.app/anaghanisakar-logo.png",
              "description": "Frontend Developer skilled in Vue, Nuxt, React, and Next.js.",
              "sameAs": [
                "https://www.linkedin.com/in/anagha-nisakar/",
                "https://github.com/anagha-nisakar"
              ]
            })
          }}
        />

        {/* Organization Schema */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "Anagha Nisakar",
              "url": "https://anagha-nisakar-portfolio.vercel.app/",
              "logo": "https://anagha-nisakar-portfolio.vercel.app/anaghanisakar-logo.png"
            })
          }}
        />
      </head>

      <body
        className={`${geistSans.variable} ${manrope?.variable} ${geologica.variable}  antialiased`}
      >
        <NavBar />
        {children}
        <section className=" border-t-1 border-b-1 border-dashed border-borderDark">
          <Contact />
        </section>
      </body>
    </html>
  );
}
