import type { Metadata } from "next";
import { JetBrains_Mono, Manrope,Geologica } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/core/NavBar";
import Contact from '@/components/landing/dev2/contact'

const geistSans = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geologica = Geologica({
  variable: "--font-geologica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anagha Nisakar | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${manrope?.variable} ${geologica.variable}  antialiased`}
      >
        <NavBar />
        {children}
        <section className=" border-t-1 border-b-1 border-dashed border-borderDark">
                <Contact />
            </section>
      </body>
    </html>
  );
}
